[32m2025-10-23 20:51:18 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e2ae5eac-1815-489d-9724-3a9393c5fbd3 - 198380 - LOGS_CAPTURED - Started capturing logs in process (pid: 198380).
[32m2025-10-23 20:51:18 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e2ae5eac-1815-489d-9724-3a9393c5fbd3 - 198380 - parse_consultations_data - STEP_START - Started execution of step "parse_consultations_data".
[32m2025-10-23 20:51:18 -0600[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - e2ae5eac-1815-489d-9724-3a9393c5fbd3 - 198380 - parse_consultations_data - STEP_FAILURE - Execution of step "parse_consultations_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "parse_consultations_data"::

NameError: name 'get_field' is not defined

Stack Trace:
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/src/dagster_quickstart/defs/assets.py", line 10, in parse_consultations_data
    consultations['day_note_consultation_observation'] = consultations['closure'].apply(lambda x: get_field(x, 'consultationObservation'))
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/pandas/core/series.py", line 4943, in apply
    ).apply()
      ^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1422, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1502, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/pandas/core/base.py", line 925, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/armando/git/insurance_case/dagster-quickstart/.venv/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2999, in pandas._libs.lib.map_infer
  File "/home/armando/git/insurance_case/dagster-quickstart/src/dagster_quickstart/defs/assets.py", line 10, in <lambda>
    consultations['day_note_consultation_observation'] = consultations['closure'].apply(lambda x: get_field(x, 'consultationObservation'))
                                                                                                  ^^^^^^^^^
[0m
